# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

en:
  languageCode: en-us
  languageName: English
  weight: 1
  title: TransportX
  params:
    description: Intelligent transportation research group at Tongji University.
  menus:
    main:
      - name: Tour
        url: tour
        weight: 10
      - name: People
        url: people
        weight: 30
      - name: News
        url: post
        weight: 20
      - name: Events
        url: event
        weight: 40
      - name: Publications
        url: publication
        weight: 50
      - name: Applications
        url: application
        weight: 55
      - name: Contact
        url: contact
        weight: 60

zh:
  languageCode: zh-Hans
  languageName: 中文
  weight: 2
  title: TransportX
  params:
    description: 同济大学智能交通研究团队。
  menus:
    main:
      - name: 课题组
        url: tour
        weight: 10
      - name: 成员
        url: people
        weight: 30
      - name: 新闻动态
        url: post
        weight: 20
      - name: 活动
        url: event
        weight: 40
      - name: 论文发表
        url: publication
        weight: 50
      - name: 应用产品
        url: application
        weight: 55
      - name: 联系我们
        url: contact
        weight: 60
